export const ACTIONS = {
  START_GAME: "START_GAME",
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  NEXT_TARGET: "NEXT_TARGET",
  RESET_GAME: "RESET_GAME",
  CHANGE_LAYOUT: "CHANGE_LAYOUT",
  LOAD_HISTORY: "LOAD_HISTORY",
  FINISH_GAME: "FINISH_GAME",
  TOGGLE_TIP: "TOGGLE_TIP",
};
